#include "completion_command.h"

#include <CLI/CLI.hpp>

#include <algorithm>
#include <format>
#include <ostream>
#include <sstream>

#include "app.h"
#include "commands.h"

namespace wsldisk::cli {
namespace {

/// Subcommands that take a distribution name as their first positional.
///
/// Asked of the tree rather than listed: a command whose first positional is
/// named `distro` gets dynamic completion, and one that grows such an argument
/// gets it without anyone remembering to come back here.
[[nodiscard]] bool takes_a_distro(const CLI::App& command) {
    return std::ranges::any_of(command.get_options(), [](const CLI::Option* option) {
        return option->get_positional() && option->get_name(true, false) == "distro";
    });
}

/// Every option name a command accepts, long and short, in declaration order.
[[nodiscard]] std::vector<std::string> flags_of(const CLI::App& command) {
    std::vector<std::string> names;
    for (const CLI::Option* option : command.get_options()) {
        if (option->get_positional()) {
            continue;
        }
        for (const std::string& name : option->get_lnames()) {
            names.push_back("--" + name);
        }
        for (const std::string& name : option->get_snames()) {
            names.push_back("-" + name);
        }
    }
    return names;
}

/// The subcommands of `app`, in declaration order.
[[nodiscard]] std::vector<const CLI::App*> subcommands_of(const CLI::App& app) {
    std::vector<const CLI::App*> commands;
    for (const CLI::App* command : app.get_subcommands({})) {
        commands.push_back(command);
    }
    return commands;
}

/// Wraps text in single quotes for a POSIX shell, escaping any it contains.
///
/// Command descriptions are prose written by us -- "Tell one distribution's
/// filesystem to release unused blocks" -- and an apostrophe in one of them
/// closes the quote and breaks the script. Found exactly that way.
[[nodiscard]] std::string shell_quoted(std::string_view text) {
    std::string result = "'";
    for (const char character : text) {
        if (character == '\'') {
            // The only way out of a single-quoted shell string: close it, emit
            // an escaped quote, open it again.
            result += R"('\'')";
            continue;
        }
        result += character;
    }
    result += '\'';
    return result;
}

/// The names a command completes to after itself: its own subcommands, if it
/// has any. `config` has four verbs, and offering none of them would make the
/// completion worse than nothing there.
[[nodiscard]] std::vector<std::string> verbs_of(const CLI::App& command) {
    std::vector<std::string> names;
    for (const CLI::App* verb : command.get_subcommands({})) {
        names.push_back(verb->get_name());
    }
    return names;
}

[[nodiscard]] std::string joined(const std::vector<std::string>& items, std::string_view separator) {
    std::string text;
    for (const std::string& item : items) {
        if (!text.empty()) {
            text += separator;
        }
        text += item;
    }
    return text;
}

/// Names quoted for a PowerShell array literal.
[[nodiscard]] std::string powershell_list(const std::vector<std::string>& items) {
    std::vector<std::string> quoted;
    quoted.reserve(items.size());
    for (const std::string& item : items) {
        quoted.push_back("'" + item + "'");
    }
    return joined(quoted, ", ");
}

[[nodiscard]] std::string powershell_script(const CLI::App& app) {
    std::ostringstream out;
    out << "# PowerShell completions for wsldisk. Generated by `wsldisk completion powershell`;\n"
           "# regenerate it after upgrading rather than editing it.\n"
           "#\n"
           "# Add to your profile:\n"
           "#   wsldisk completion powershell | Out-String | Invoke-Expression\n\n";

    std::vector<std::string> names;
    out << "$script:WsldiskCommands = @{\n";
    for (const CLI::App* command : subcommands_of(app)) {
        names.push_back(command->get_name());
        // A command's own verbs complete alongside its flags.
        std::vector<std::string> candidates = verbs_of(*command);
        const std::vector<std::string> flags = flags_of(*command);
        candidates.insert(candidates.end(), flags.begin(), flags.end());
        out << "    '" << command->get_name() << "' = @(" << powershell_list(candidates) << ")\n";
    }
    out << "}\n\n";

    out << "$script:WsldiskGlobal = @(" << powershell_list(flags_of(app)) << ")\n\n";

    // Asked for at completion time, not baked in: the answer changes between
    // one invocation and the next.
    out << "function script:WsldiskDistros {\n"
           "    try {\n"
           "        (wsldisk list --json 2>$null) |\n"
           "            ForEach-Object { ($_ | ConvertFrom-Json).name } |\n"
           "            Where-Object { $_ }\n"
           "    } catch {\n"
           "        @()\n"
           "    }\n"
           "}\n\n";

    out << "$script:WsldiskTakesDistro = @(";
    std::vector<std::string> with_distro;
    for (const CLI::App* command : subcommands_of(app)) {
        if (takes_a_distro(*command)) {
            with_distro.push_back(command->get_name());
        }
    }
    out << powershell_list(with_distro) << ")\n\n";

    out << "Register-ArgumentCompleter -Native -CommandName wsldisk -ScriptBlock {\n"
           "    param($wordToComplete, $commandAst, $cursorPosition)\n\n"
           "    $words = @($commandAst.CommandElements | ForEach-Object { $_.ToString() })\n"
           "    $command = $words | Select-Object -Skip 1 |\n"
           "        Where-Object { -not $_.StartsWith('-') } | Select-Object -First 1\n\n"
           "    $candidates = if (-not $command -or -not $script:WsldiskCommands.ContainsKey($command)) {\n"
           "        @($script:WsldiskCommands.Keys) + $script:WsldiskGlobal\n"
           "    } elseif ($wordToComplete.StartsWith('-')) {\n"
           "        $script:WsldiskCommands[$command]\n"
           "    } elseif ($script:WsldiskTakesDistro -contains $command) {\n"
           "        WsldiskDistros\n"
           "    } else {\n"
           "        $script:WsldiskCommands[$command]\n"
           "    }\n\n"
           "    $candidates | Where-Object { $_ -like \"$wordToComplete*\" } | Sort-Object |\n"
           "        ForEach-Object {\n"
           "            [System.Management.Automation.CompletionResult]::new(\n"
           "                $_, $_, 'ParameterValue', $_)\n"
           "        }\n"
           "}\n";
    return out.str();
}

[[nodiscard]] std::string bash_script(const CLI::App& app) {
    std::ostringstream out;
    out << "# bash completions for wsldisk. Generated by `wsldisk completion bash`;\n"
           "# regenerate it after upgrading rather than editing it.\n"
           "#\n"
           "# Add to your profile:\n"
           "#   source <(wsldisk completion bash)\n\n";

    std::vector<std::string> names;
    for (const CLI::App* command : subcommands_of(app)) {
        names.push_back(command->get_name());
    }

    out << "_wsldisk() {\n";
    out << "    local commands='" << joined(names, " ") << "'\n";
    out << "    local global='" << joined(flags_of(app), " ") << "'\n";
    out << "    local with_distro='";
    std::vector<std::string> with_distro;
    for (const CLI::App* command : subcommands_of(app)) {
        if (takes_a_distro(*command)) {
            with_distro.push_back(command->get_name());
        }
    }
    out << joined(with_distro, " ") << "'\n\n";

    out << "    local cur prev command word\n"
           "    cur=\"${COMP_WORDS[COMP_CWORD]}\"\n"
           "    command=''\n"
           "    for word in \"${COMP_WORDS[@]:1:COMP_CWORD-1}\"; do\n"
           "        case \"$word\" in\n"
           "            -*) ;;\n"
           "            *) command=\"$word\"; break ;;\n"
           "        esac\n"
           "    done\n\n";

    out << "    local flags=''\n"
           "    case \"$command\" in\n";
    for (const CLI::App* command : subcommands_of(app)) {
        // A command's own verbs complete alongside its flags: `config <TAB>`
        // offering nothing would be worse than no completion at all there.
        std::vector<std::string> candidates = verbs_of(*command);
        const std::vector<std::string> flags = flags_of(*command);
        candidates.insert(candidates.end(), flags.begin(), flags.end());
        out << "        " << command->get_name() << ") flags='" << joined(candidates, " ") << "' ;;\n";
    }
    out << "        *) COMPREPLY=($(compgen -W \"$commands $global\" -- \"$cur\")); return ;;\n"
           "    esac\n\n";

    // Asked for at completion time, not baked in.
    out << "    if [[ \"$cur\" != -* ]] && [[ \" $with_distro \" == *\" $command \"* ]]; then\n"
           "        local distros\n"
           "        distros=$(wsldisk list --json 2>/dev/null |\n"
           "            sed -n 's/.*\"name\"[[:space:]]*:[[:space:]]*\"\\([^\"]*\\)\".*/\\1/p')\n"
           "        COMPREPLY=($(compgen -W \"$distros\" -- \"$cur\"))\n"
           "        return\n"
           "    fi\n\n"
           "    COMPREPLY=($(compgen -W \"$flags\" -- \"$cur\"))\n"
           "}\n\n"
           "complete -F _wsldisk wsldisk\n";
    return out.str();
}

[[nodiscard]] std::string zsh_script(const CLI::App& app) {
    std::ostringstream out;
    out << "#compdef wsldisk\n"
           "# zsh completions for wsldisk. Generated by `wsldisk completion zsh`;\n"
           "# regenerate it after upgrading rather than editing it.\n"
           "#\n"
           "# Add to your profile:\n"
           "#   source <(wsldisk completion zsh)\n\n";

    // A custom delimiter: the script contains `)"`, which would end a plain
    // raw string literal in the middle of the zsh substitution.
    out << R"ZSH(_wsldisk_distros() {
    local -a names
    names=(${(f)"$(wsldisk list --json 2>/dev/null |
        sed -n 's/.*"name"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p')"})
    _describe 'distribution' names
}

)ZSH";

    out << "_wsldisk() {\n"
           "    local -a commands\n"
           "    commands=(\n";
    for (const CLI::App* command : subcommands_of(app)) {
        // The description goes in the menu, which is most of why zsh completion
        // is worth generating rather than listing names. Quoted, because those
        // descriptions are prose and some of them contain an apostrophe.
        out << "        " << shell_quoted(command->get_name() + ":" + command->get_description()) << '\n';
    }
    out << "    )\n\n";

    out << "    _arguments -C \\\n";
    for (const std::string& flag : flags_of(app)) {
        out << "        '" << flag << "' \\\n";
    }
    out << "        '1: :{_describe \"command\" commands}' \\\n"
           "        '*:: :->args'\n\n";

    out << "    case $state in\n"
           "        args)\n"
           "            case $words[1] in\n";
    for (const CLI::App* command : subcommands_of(app)) {
        out << "                " << command->get_name() << ")\n";
        out << "                    _arguments";
        for (const std::string& flag : flags_of(*command)) {
            out << " \\\n                        '" << flag << "'";
        }
        if (takes_a_distro(*command)) {
            out << " \\\n                        '1: :_wsldisk_distros'";
        } else if (const std::vector<std::string> verbs = verbs_of(*command); !verbs.empty()) {
            // A command with verbs of its own -- `config get`, `config set` --
            // completes to those rather than to nothing.
            out << " \\\n                        '1: :(" << joined(verbs, " ") << ")'";
        }
        out << "\n                    ;;\n";
    }
    out << "            esac\n"
           "            ;;\n"
           "    esac\n"
           "}\n\n"
           "_wsldisk \"$@\"\n";
    return out.str();
}

}  // namespace

std::vector<std::string> completion_shells() {
    return {"powershell", "bash", "zsh"};
}

std::string generate_completion(const CLI::App& app, std::string_view shell) {
    if (shell == "powershell") {
        return powershell_script(app);
    }
    if (shell == "bash") {
        return bash_script(app);
    }
    return zsh_script(app);
}

int run_completion(const CompletionOptions& options, const GlobalOptions& global, std::ostream& out,
                   std::ostream& err) {
    const std::vector<std::string> shells = completion_shells();
    if (std::ranges::find(shells, options.shell) == shells.end()) {
        return report(Error{ErrorCode::Usage, std::format("there is no completion for `{}`", options.shell),
                            std::format("the shells are: {}", joined(shells, ", "))},
                      global, out, err);
    }

    // A throwaway tree, built by the same function that builds the real one, so
    // the script can only ever describe the flags that exist.
    CLI::App app{"Compact, shrink, move, inspect and snapshot WSL2 virtual disks", "wsldisk"};
    CommandOptions unused;
    add_all_commands(app, unused);

    out << generate_completion(app, options.shell);
    return exit_code_success;
}

void add_completion_command(CLI::App& app, GlobalOptions& global, CompletionOptions& options) {
    CLI::App* completion = app.add_subcommand("completion", "Print a shell completion script for wsldisk");
    add_global_options(*completion, global);
    completion->add_option("shell", options.shell, "powershell, bash or zsh")
        ->option_text("SHELL")
        ->required();
}

}  // namespace wsldisk::cli
