# bash completions for wsldisk. Generated by `wsldisk completion bash`;
# regenerate it after upgrading rather than editing it.
#
# Add to your profile:
#   source <(wsldisk completion bash)

_wsldisk() {
    local commands='list info orphans trim compact config completion'
    local global='--help -h --version -V --json --verbose -v --yes -y --dry-run --log'
    local with_distro='info trim compact'

    local cur prev command word
    cur="${COMP_WORDS[COMP_CWORD]}"
    command=''
    for word in "${COMP_WORDS[@]:1:COMP_CWORD-1}"; do
        case "$word" in
            -*) ;;
            *) command="$word"; break ;;
        esac
    done

    local flags=''
    case "$command" in
        list) flags='--help -h --json --verbose -v --yes -y --dry-run --log --probe' ;;
        info) flags='--help -h --json --verbose -v --yes -y --dry-run --log --probe' ;;
        orphans) flags='--help -h --json --verbose -v --yes -y --dry-run --log --scan --delete --relink --to' ;;
        trim) flags='--help -h --json --verbose -v --yes -y --dry-run --log' ;;
        compact) flags='--help -h --json --verbose -v --yes -y --dry-run --log --all --file --no-trim --restart --shutdown' ;;
        config) flags='path get set edit --help -h --json --verbose -v --yes -y --dry-run --log' ;;
        completion) flags='--help -h --json --verbose -v --yes -y --dry-run --log' ;;
        *) COMPREPLY=($(compgen -W "$commands $global" -- "$cur")); return ;;
    esac

    if [[ "$cur" != -* ]] && [[ " $with_distro " == *" $command "* ]]; then
        local distros
        distros=$(wsldisk list --json 2>/dev/null |
            sed -n 's/.*"name"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p')
        COMPREPLY=($(compgen -W "$distros" -- "$cur"))
        return
    fi

    COMPREPLY=($(compgen -W "$flags" -- "$cur"))
}

complete -F _wsldisk wsldisk
