# bash completions for wsldisk. Generated by `wsldisk completion bash`;
# regenerate it after upgrading rather than editing it.
#
# Add to your profile:
#   source <(wsldisk completion bash)

_wsldisk() {
    local commands='list info orphans relink trim compact config completion'
    local global='--help -h --version -V --json --verbose -v --yes -y --dry-run --log'
    local distro_slots=' info:0 relink:0 trim:0 compact:0 '
    local path_slots=' relink:1 '

    local cur prev command word
    cur="${COMP_WORDS[COMP_CWORD]}"
    command=''
    local positional=-1
    for word in "${COMP_WORDS[@]:1:COMP_CWORD-1}"; do
        case "$word" in
            -*) ;;
            *)
                if [[ -z "$command" ]]; then
                    command="$word"
                else
                    positional=$((positional + 1))
                fi
                ;;
        esac
    done
    positional=$((positional + 1))

    local flags=''
    case "$command" in
        list) flags='--help -h --json --verbose -v --yes -y --dry-run --log --probe' ;;
        info) flags='--help -h --json --verbose -v --yes -y --dry-run --log --probe' ;;
        orphans) flags='--help -h --json --verbose -v --yes -y --dry-run --log --scan --delete --relink --to' ;;
        relink) flags='--help -h --json --verbose -v --yes -y --dry-run --log' ;;
        trim) flags='--help -h --json --verbose -v --yes -y --dry-run --log' ;;
        compact) flags='--help -h --json --verbose -v --yes -y --dry-run --log --all --file --no-trim --restart --shutdown' ;;
        config) flags='path get set edit --help -h --json --verbose -v --yes -y --dry-run --log' ;;
        completion) flags='--help -h --json --verbose -v --yes -y --dry-run --log' ;;
        *) COMPREPLY=($(compgen -W "$commands $global" -- "$cur")); return ;;
    esac

    local slot="$command:$positional"
    if [[ "$cur" != -* ]] && [[ "$distro_slots" == *" $slot "* ]]; then
        local distros
        distros=$(wsldisk list --json 2>/dev/null |
            sed -n 's/.*"name"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p')
        COMPREPLY=($(compgen -W "$distros" -- "$cur"))
        return
    fi

    if [[ "$cur" != -* ]] && [[ "$path_slots" == *" $slot "* ]]; then
        COMPREPLY=($(compgen -f -- "$cur"))
        return
    fi

    COMPREPLY=($(compgen -W "$flags" -- "$cur"))
}

complete -F _wsldisk wsldisk
