# PowerShell completions for wsldisk. Generated by `wsldisk completion powershell`;
# regenerate it after upgrading rather than editing it.
#
# Add to your profile:
#   wsldisk completion powershell | Out-String | Invoke-Expression

$script:WsldiskCommands = @{
    'list' = @('--help', '-h', '--json', '--verbose', '-v', '--yes', '-y', '--dry-run', '--log', '--probe')
    'info' = @('--help', '-h', '--json', '--verbose', '-v', '--yes', '-y', '--dry-run', '--log', '--probe')
    'orphans' = @('--help', '-h', '--json', '--verbose', '-v', '--yes', '-y', '--dry-run', '--log', '--scan', '--delete', '--relink', '--to')
    'trim' = @('--help', '-h', '--json', '--verbose', '-v', '--yes', '-y', '--dry-run', '--log')
    'compact' = @('--help', '-h', '--json', '--verbose', '-v', '--yes', '-y', '--dry-run', '--log', '--all', '--file', '--no-trim', '--restart', '--shutdown')
    'config' = @('path', 'get', 'set', 'edit', '--help', '-h', '--json', '--verbose', '-v', '--yes', '-y', '--dry-run', '--log')
    'completion' = @('--help', '-h', '--json', '--verbose', '-v', '--yes', '-y', '--dry-run', '--log')
}

$script:WsldiskGlobal = @('--help', '-h', '--version', '-V', '--json', '--verbose', '-v', '--yes', '-y', '--dry-run', '--log')

function script:WsldiskDistros {
    try {
        (wsldisk list --json 2>$null) |
            ForEach-Object { ($_ | ConvertFrom-Json).name } |
            Where-Object { $_ }
    } catch {
        @()
    }
}

$script:WsldiskTakesDistro = @('info', 'trim', 'compact')

Register-ArgumentCompleter -Native -CommandName wsldisk -ScriptBlock {
    param($wordToComplete, $commandAst, $cursorPosition)

    $words = @($commandAst.CommandElements | ForEach-Object { $_.ToString() })
    $command = $words | Select-Object -Skip 1 |
        Where-Object { -not $_.StartsWith('-') } | Select-Object -First 1

    $candidates = if (-not $command -or -not $script:WsldiskCommands.ContainsKey($command)) {
        @($script:WsldiskCommands.Keys) + $script:WsldiskGlobal
    } elseif ($wordToComplete.StartsWith('-')) {
        $script:WsldiskCommands[$command]
    } elseif ($script:WsldiskTakesDistro -contains $command) {
        WsldiskDistros
    } else {
        $script:WsldiskCommands[$command]
    }

    $candidates | Where-Object { $_ -like "$wordToComplete*" } | Sort-Object |
        ForEach-Object {
            [System.Management.Automation.CompletionResult]::new(
                $_, $_, 'ParameterValue', $_)
        }
}
