#compdef wsldisk
# zsh completions for wsldisk. Generated by `wsldisk completion zsh`;
# regenerate it after upgrading rather than editing it.
#
# Add to your profile:
#   source <(wsldisk completion zsh)

_wsldisk_distros() {
    local -a names
    names=(${(f)"$(wsldisk list --json 2>/dev/null |
        sed -n 's/.*"name"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p')"})
    _describe 'distribution' names
}

_wsldisk() {
    local -a commands
    commands=(
        'list:List every registered distribution and its disk'
        'info:Show everything known about one distribution'
        'orphans:Find virtual disks that no distribution claims'
        'relink:Point a distribution at a virtual disk that has been moved'
        'trim:Tell one distribution'\''s filesystem to release unused blocks'
        'compact:Reclaim the unused space in a virtual disk'
        'config:Show or change wsldisk'\''s settings'
        'completion:Print a shell completion script for wsldisk'
    )

    _arguments -C \
        '--help' \
        '-h' \
        '--version' \
        '-V' \
        '--json' \
        '--verbose' \
        '-v' \
        '--yes' \
        '-y' \
        '--dry-run' \
        '--log' \
        '1: :{_describe "command" commands}' \
        '*:: :->args'

    case $state in
        args)
            case $words[1] in
                list)
                    _arguments \
                        '--help' \
                        '-h' \
                        '--json' \
                        '--verbose' \
                        '-v' \
                        '--yes' \
                        '-y' \
                        '--dry-run' \
                        '--log' \
                        '--probe'
                    ;;
                info)
                    _arguments \
                        '--help' \
                        '-h' \
                        '--json' \
                        '--verbose' \
                        '-v' \
                        '--yes' \
                        '-y' \
                        '--dry-run' \
                        '--log' \
                        '--probe' \
                        '1: :_wsldisk_distros'
                    ;;
                orphans)
                    _arguments \
                        '--help' \
                        '-h' \
                        '--json' \
                        '--verbose' \
                        '-v' \
                        '--yes' \
                        '-y' \
                        '--dry-run' \
                        '--log' \
                        '--scan' \
                        '--delete' \
                        '--relink' \
                        '--to'
                    ;;
                relink)
                    _arguments \
                        '--help' \
                        '-h' \
                        '--json' \
                        '--verbose' \
                        '-v' \
                        '--yes' \
                        '-y' \
                        '--dry-run' \
                        '--log' \
                        '1: :_wsldisk_distros' \
                        '2: :_files'
                    ;;
                trim)
                    _arguments \
                        '--help' \
                        '-h' \
                        '--json' \
                        '--verbose' \
                        '-v' \
                        '--yes' \
                        '-y' \
                        '--dry-run' \
                        '--log' \
                        '1: :_wsldisk_distros'
                    ;;
                compact)
                    _arguments \
                        '--help' \
                        '-h' \
                        '--json' \
                        '--verbose' \
                        '-v' \
                        '--yes' \
                        '-y' \
                        '--dry-run' \
                        '--log' \
                        '--all' \
                        '--file' \
                        '--no-trim' \
                        '--restart' \
                        '--shutdown' \
                        '1: :_wsldisk_distros'
                    ;;
                config)
                    _arguments \
                        '--help' \
                        '-h' \
                        '--json' \
                        '--verbose' \
                        '-v' \
                        '--yes' \
                        '-y' \
                        '--dry-run' \
                        '--log' \
                        '1: :(path get set edit)'
                    ;;
                completion)
                    _arguments \
                        '--help' \
                        '-h' \
                        '--json' \
                        '--verbose' \
                        '-v' \
                        '--yes' \
                        '-y' \
                        '--dry-run' \
                        '--log'
                    ;;
            esac
            ;;
    esac
}

_wsldisk "$@"
